name: Go

on:
  push:
    branches: [ main ]
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: build artifacts
      run: make build-multios
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          edge-extractor-win-amd64.exe
          edge-extractor-linux-386
          edge-extractor-linux-amd64
          edge-extractor-osx-amd64
          edge-extractor-osx-arm
          
