name: Go

on:
  # push:
  #   branches: [ main ]
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: Set up Go
      uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
      with:
        go-version: 1.21.3

    - name: build artifacts
      run: make build-multios
      env:
        CONFIG_ENCRYPTION_KEY: ${{ secrets.CONFIG_ENCRYPTION_KEY }}
      
    - name: Release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
      with:
        files: |
          edge-extractor-win-amd64.exe
          edge-extractor-win-arm64.exe
          edge-extractor-linux-386
          edge-extractor-linux-amd64
          edge-extractor-linux-arm
          edge-extractor-osx-amd64
          edge-extractor-osx-arm
          
